package com.yunbiao.ybsmartcheckin_live_id.db2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VISITOR".
*/
public class VisitorDao extends AbstractDao<Visitor, Long> {

    public static final String TABLENAME = "VISITOR";

    /**
     * Properties of entity Visitor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property FaceId = new Property(1, String.class, "faceId", false, "FACE_ID");
        public final static Property ComId = new Property(2, int.class, "comId", false, "COM_ID");
        public final static Property Unit = new Property(3, String.class, "unit", false, "UNIT");
        public final static Property Phone = new Property(4, String.class, "phone", false, "PHONE");
        public final static Property Sex = new Property(5, int.class, "sex", false, "SEX");
        public final static Property CurrEnd = new Property(6, String.class, "currEnd", false, "CURR_END");
        public final static Property Reason = new Property(7, String.class, "reason", false, "REASON");
        public final static Property Name = new Property(8, String.class, "name", false, "NAME");
        public final static Property Head = new Property(9, String.class, "head", false, "HEAD");
        public final static Property CurrStart = new Property(10, String.class, "currStart", false, "CURR_START");
        public final static Property HeadPath = new Property(11, String.class, "headPath", false, "HEAD_PATH");
        public final static Property AddTag = new Property(12, int.class, "addTag", false, "ADD_TAG");
        public final static Property VisEntryId = new Property(13, long.class, "visEntryId", false, "VIS_ENTRY_ID");
    }


    public VisitorDao(DaoConfig config) {
        super(config);
    }
    
    public VisitorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VISITOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"FACE_ID\" TEXT UNIQUE ," + // 1: faceId
                "\"COM_ID\" INTEGER NOT NULL ," + // 2: comId
                "\"UNIT\" TEXT," + // 3: unit
                "\"PHONE\" TEXT," + // 4: phone
                "\"SEX\" INTEGER NOT NULL ," + // 5: sex
                "\"CURR_END\" TEXT," + // 6: currEnd
                "\"REASON\" TEXT," + // 7: reason
                "\"NAME\" TEXT," + // 8: name
                "\"HEAD\" TEXT," + // 9: head
                "\"CURR_START\" TEXT," + // 10: currStart
                "\"HEAD_PATH\" TEXT," + // 11: headPath
                "\"ADD_TAG\" INTEGER NOT NULL ," + // 12: addTag
                "\"VIS_ENTRY_ID\" INTEGER NOT NULL );"); // 13: visEntryId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VISITOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Visitor entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String faceId = entity.getFaceId();
        if (faceId != null) {
            stmt.bindString(2, faceId);
        }
        stmt.bindLong(3, entity.getComId());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(4, unit);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
        stmt.bindLong(6, entity.getSex());
 
        String currEnd = entity.getCurrEnd();
        if (currEnd != null) {
            stmt.bindString(7, currEnd);
        }
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(8, reason);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(9, name);
        }
 
        String head = entity.getHead();
        if (head != null) {
            stmt.bindString(10, head);
        }
 
        String currStart = entity.getCurrStart();
        if (currStart != null) {
            stmt.bindString(11, currStart);
        }
 
        String headPath = entity.getHeadPath();
        if (headPath != null) {
            stmt.bindString(12, headPath);
        }
        stmt.bindLong(13, entity.getAddTag());
        stmt.bindLong(14, entity.getVisEntryId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Visitor entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String faceId = entity.getFaceId();
        if (faceId != null) {
            stmt.bindString(2, faceId);
        }
        stmt.bindLong(3, entity.getComId());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(4, unit);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
        stmt.bindLong(6, entity.getSex());
 
        String currEnd = entity.getCurrEnd();
        if (currEnd != null) {
            stmt.bindString(7, currEnd);
        }
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(8, reason);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(9, name);
        }
 
        String head = entity.getHead();
        if (head != null) {
            stmt.bindString(10, head);
        }
 
        String currStart = entity.getCurrStart();
        if (currStart != null) {
            stmt.bindString(11, currStart);
        }
 
        String headPath = entity.getHeadPath();
        if (headPath != null) {
            stmt.bindString(12, headPath);
        }
        stmt.bindLong(13, entity.getAddTag());
        stmt.bindLong(14, entity.getVisEntryId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Visitor readEntity(Cursor cursor, int offset) {
        Visitor entity = new Visitor( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // faceId
            cursor.getInt(offset + 2), // comId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // unit
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone
            cursor.getInt(offset + 5), // sex
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // currEnd
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // reason
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // name
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // head
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // currStart
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // headPath
            cursor.getInt(offset + 12), // addTag
            cursor.getLong(offset + 13) // visEntryId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Visitor entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setFaceId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setComId(cursor.getInt(offset + 2));
        entity.setUnit(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSex(cursor.getInt(offset + 5));
        entity.setCurrEnd(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setReason(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setHead(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCurrStart(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setHeadPath(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAddTag(cursor.getInt(offset + 12));
        entity.setVisEntryId(cursor.getLong(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Visitor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Visitor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Visitor entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
